import datetime
from pathlib import Path
from tempfile import TemporaryDirectory

from pgr import log
from pgr.change_log import generate_change_chapters
from pgr.config import ReleaseConfig
from pgr.conv_commit.resolver import GroupedConvCommits
from pgr.interfaces import NewVersion


class ChangelogGenerator:
    def __init__(self, config: ReleaseConfig, temp_dir: TemporaryDirectory):
        self.config = config
        self.temp_dir = temp_dir

    def generate_changelog(self, grouped_commits: GroupedConvCommits, current_version: str | None,
                           next_version: NewVersion):
        new_change_md = self.__generate_change_log_new_version(grouped_commits, next_version, current_version)
        log.debug("The new changelog entry:\n%s", new_change_md)

        file_path = f"{self.temp_dir.name}/{self.config.changelog_file}"
        if Path(file_path).exists():
            with open(file_path, "r", encoding="UTF-8") as f:
                changelog_content = f.readlines()
        else:
            changelog_content = []

        with open(file_path, "w+", encoding="UTF-8") as f:
            if len(changelog_content) == 0:
                file_content = self.__create_new_changelog(new_change_md)
            else:
                file_content = self.__append_new_changelog(changelog_content, new_change_md)

            f.write(file_content)

    def __create_new_changelog(self, change_md: str):
        log.info("No %s file is present. Creating one...", self.config.changelog_file)
        change_parts = ["## Changelog"]
        change_parts.extend(change_md.splitlines())
        change_parts.extend(["---", "generated by git-release"])
        return "\n".join(change_parts)

    def __append_new_changelog(self, current_changelog: list[str], new_change_md: str) -> str:
        log.info("%s changelog file is present. Updating...", self.config.changelog_file)
        change_parts = [
            change_part.strip()
            for change_part in current_changelog
        ]
        change_parts[1:1] = new_change_md.splitlines()
        return "\n".join(change_parts)

    def __generate_change_log_new_version(self, grouped_commits: GroupedConvCommits, new_version: NewVersion,
                                          current_version: str | None = None) -> str:
        release_url = f"{self.config.git_url()}/releases/tag/{new_version.get_full_version()}"
        new_changes = f"## [{new_version.get_full_version()}]({release_url}) (📅 {datetime.datetime.now().strftime("%Y-%m-%d")}\n)"
        if grouped_commits.has_breaking_change():
            new_changes += "\n".join(generate_change_chapters("Breaking changes",
                                                                           [grouped_commits.braking_changes]))
        if grouped_commits.has_feature():
            new_changes += "\n".join(generate_change_chapters("Features",
                                                                           [grouped_commits.get_features()]))
        if grouped_commits.has_fix():
            new_changes += "\n".join(generate_change_chapters("Bugfix(es)",
                                                                           [grouped_commits.get_fixes()]))
        if grouped_commits.has_other_change():
            new_changes += "\n".join(generate_change_chapters("Other changes",
                                                                           [grouped_commits.get_other_changes(),
                                                                            grouped_commits.invalid_commits], True))
        if current_version is not None:
            compare_text = f"{current_version}...{new_version.get_full_version()}"
            new_changes += f"#### Full changelog: [{compare_text}](https://gitea.raspi.zolkiss.home/KiZoCo/testing-repository-with-releases/compare/{compare_text})\n"
        # This may be implemented later...
        # new_changes += "#" + os.linesep
        # new_changes += "#### contributors: " + os.linesep
        new_changes += "---\n"
        return new_changes

    # @staticmethod
    # def __generate_change_chapters(chapter_title: str, changes: list[list[ConvCommitDetails]],
    #                                include_type: bool = False) -> list[str]:
    #     change_chapter = [f"### {chapter_title}"]
    #     if len(changes) == 1:
    #         final_changes = changes[0]
    #     else:
    #         final_changes = []
    #         for change in changes:
    #             final_changes.extend(change)
    #
    #     sorted_list = sorted(final_changes, key=lambda x: x.creation_datetime, reverse=True)
    #
    #     change_chapter.extend(ChangelogGenerator.__generate_change_records(sorted_list, include_type))
    #     change_chapter.extend([""])
    #     return change_chapter
    #
    # @staticmethod
    # def __generate_change_records(changes: list[ConvCommitDetails], include_type: bool) -> list[
    #     str]:
    #     change_records = []
    #     for change in changes:
    #         if change.valid:
    #             if change.scope is not None and include_type:
    #                 scope = f"**{change.type}({change.scope}):**"
    #             elif change.scope is not None:
    #                 scope = f"**{change.scope}:**"
    #             else:
    #                 scope = ""
    #             change_records.append(f"* {scope} {change.description}")
    #         else:
    #             change_records.append(f"* {change.description}")
    #     return change_records
