@startuml
<style>
    .finished {
        BackgroundColor: #80EF80
    }
</style>
start
:Find the latest merged release PR; <<finished>>
:Find all the unreleased release PRs; <<finished>>
:Get oldest unreleased release PR; <<finished>>
repeat :Get previous release PR or None; <<finished>>
    :Parse the actual version from the commit name; <<finished>>
    if(Version already exists for that change?) then (no) <<finished>>
        :Create Release for the commit; <<finished>>
    else (yes)
    endif
backward :Get the next oldest unreleased PR; <<finished>>
repeat while (Does have more unreleased PRs?) is (yes)
->no;
stop
@enduml