@startuml
<style>
    .finished {
        BackgroundColor: #80EF80
    }
</style>
start
if(Does have a release branch?) then (no) <<finished>>
    :Create release branch from the latest default; <<finished>>
else (yes)
    :Checkout release branch; <<finished>>
    :Rebase to the lastest default; <<finished>>
endif
:Get latest release reference; <<finished>>
if(Has unreleased release PR?) then (yes) <<finished>>
    :Update latest release reference; <<finished>>
endif
if(Is the latest release reference valid?) then (yes) <<finished>>
    :Collect commits since the last release PR; <<finished>>
else (no)
    :Collect commits from the beginning; <<finished>>
endif
:Filter commits with conventional commit message; <<finished>>
:Calculate next version; <<finished>>
:Generate changelog based on conventional commit rules; <<finished>>
:Update files based on the config (Changelog.md, version.txt, etc.); <<finished>>
:Force push release branch; <<finished>>
:Re-generate PR 1st commit message; <<finished>>

stop
@enduml